name: forum

volumes:
  pgdata:

services:
  db:
    image: forum-postgres
    build: ./postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./volumes/pgconfig:/app/config

  redis:
    image: forum-redis
    build: ./redis

  backend:
    image: forum-backend
    build: ./forum-laravel
    ports:
      - 8080:80
    volumes:
      - ./volumes/backend/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/backend/www.conf:/etc/php82/php-fpm.d/www.conf
      - ./volumes/backend/php.ini:/etc/php82/php.ini
    environment:
      - RUN_MIGRATIONS=false
      - RUN_DB_SEED=false
      - DB_HOST=db
      - DB_DATABASE=app
      - DB_USERNAME=app_server
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - CORS_URL=http://localhost
      - APP_DEBUG=true
      - APP_ENV=local

  frontend:
    image: forum-frontend
    build: ./forum-vue
    ports:
      - 80:80
    volumes:
      - ./volumes/frontend/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VITE_API_URL=http://api.localhost:8080
